### ISSUE TITLE
vb30 missleading bug

### ISSUE THREAD

**Issue by witaj** [bdancer/blender-for-vray#95]
![przechwytywanie](https://cloud.githubusercontent.com/assets/1749900/7460432/46dc029a-f2a3-11e4-8bb1-7b618f8a4a18.PNG)

Hi there is small bug with displaying DMC threshold, when option "use dmc sampler threshold" is unticked threshold slider should be active. 

As well I do not know if thats how it shoud be when type is set to Adaptive DMC, there are sliders and option to set progressive sampler which is missleading.

Thanks

**Comment by bdancer** [comment]
Thans! The panel drawing was completely incorrect actually =) Fixed with https://github.com/bdancer/vb30/commit/5d9a13cbf1cd9a147b8709fdc7645279a4b62dbb, https://github.com/bdancer/vb30/commit/589632d5c16ffa555842d0405a8ae6dad1b18a90 and https://github.com/bdancer/plugins_desc/commit/fb1e37190c2b7bfc166dfde0b389d720f3c3dac9

**Comment by kontrolermpl** [comment]
Oh right... that completely change everything. THX!
